services:
  codex:
    build: ./codex
#    ports: # use if it is necessary to expose the container to the host machine
#      - "3000:3000"
    environment:
      ARGON_PEPPER: secret_pepper
      UPLOADS_SECRET: uploadsSecret
      UPLOADS_IP: codex
      UPLOADS_PORT: 3001
    develop:
      watch:
        - action: sync+restart
          path: ./codex
          target: /usr/src/app/
          ignore:
            - node_modules/
  uploads:
    build: ./uploads
#    ports: # use if it is necessary to expose the container to the host machine
#      - "3000:3000"
    environment:
      UPLOADS_SECRET: uploadsSecret
    develop:
      watch:
        - action: sync+restart
          path: ./uploads
          target: /usr/src/app/
          ignore:
            - node_modules/
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: prod
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  # An industry standard secure server recommended by experts which we use as a reverse proxy with HTTPS
  caddy:
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
#      - caddy_data:/data
#      - caddy_config:/config

volumes:
  pg_data:
#  caddy_data:
#  caddy_config:
