services:
#  dev-codex:
#    image: "node:23.9.0-slim@sha256:dcacc1ee3b03a497c2096b0084d3a67b856e777b55ffccfcc76bcdab9cc65906"
#    user: "node"
#    working_dir: /home/node/app
#    volumes:
#      - ./:/home/node/app
#    command: "npm start"
#    ports: # use if it is necessary to expose the container to the host machine
#      - "3000:3000"
  codex:
    build: .
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"

    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app/
          ignore:
            - node_modules/
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  pg_data:
